{% set version = "0.9-4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cramer
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cramer_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cramer/cramer_{{ version }}.tar.gz
  sha256: 834d3fd5cfd87bb9b8f0b507217fcd3eece05b8ca34d00f20a15dd2c427ab844

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-boot                       # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-boot
    - r-rcpp >=1.0.12
  run:
    - r-base
    - r-boot
    - r-rcpp >=1.0.12
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('cramer')"           # [not win]
    - "\"%R%\" -e \"library('cramer')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=cramer
  license: GPL-2.0-or-later
  summary: Provides R routine for the so called two-sample Cramer-Test.  This nonparametric two-sample-test on equality of the underlying distributions can be applied to  multivariate data as well as univariate data. It offers two  possibilities to approximate the critical value both of which  are included in this package.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
