travis:
  secure:
    BINSTAR_TOKEN: oQld2I0Am5MTEepiWxTjVmrgn5HV67eL3heu1c50zgkD19aLKD1wWtxypbcAF7nOjzT+CDhYyoUIL0Y8FkZcIaW113JxfHMQxOowFDBcpyLuLJxaigqDUDLjvFU4725TIyu+XtJAI7PuJGzNXiDL0tOJO8/2dpqEq5svq6SODiaM2cq2DejU1KrZR7KGzRI2a0+kqI6eLQ1YwhsClCksySEyjNDDzkA1TdZrk7hQl3o09QNEXN0mC2p8LDAGSUPvprUqYOqbqE3rGkrvzK4v1BUAYrAoPdX+erwntUoGM599UNNc6ud5jFfRn16sN4IfcTTEcfWZEP9JefeGqva4nOsDltWJlAxoFg55mND2H/sBCJxhNhSGbqDlbKxfYl9ICWVlWS9H51dQZ8W5SlFpbNJa9me7aDE2a0NLrCSGCyxvcfmMHbuLapA/3YfyNobAnEMo9jR2iO8cBtdYz/YzWu8sMJCCokzUsR22ofrFKXa1MjKvS++X01w05hu/A+8R9lroPZKL3PvW0PjZJ3z6YG2d7kmNvVVb78mhlfiYsLyW1oPyVQzpyRtCHavPL0efCopQCRisHjinEXO2eUMyLQ1P/t5ElvCCzOjWwzp/LmOszTf1sbEbbav7ktEGPkVN1pNQOHAD2O/hQb7AgNUZd2Z0JNfbZIjWctuJSkwjXW4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
