travis:
  secure:
    BINSTAR_TOKEN: INDFHnSQvitO2ld/UynwdCxwqwVYqSIlZV2noXcmQ3MG6/AO7xyWqBGA+Dp8KPScQ03F31qzfvIRX0MU3rwf/EBGIBmndhw8iOfQd8pvTiehAX0RfHHcBPRpSBIPTVEFnKkleK4yzBJnK/Vi8axBiqc8yr9BMqJewPhUUUZ2/ugJLQf34aA927ABWDP1K1IHHr7Degv8gP0YSglHrCpOBtAA2UaymjdBFo7UDViAWZ+F6MBzuH4M7/qf0/5KWr7YQk5ny6ZoJStwf+ZllbPYPnKkIGmVyYSFYzS7AGmVIM57ugggTEvQ7VsPjDqH4S/DSZ4GV5N38BGFCpRmD5tB4rDUQxngP+f04sFpdZu2HuVqu2s1QueKfpvzj2FBGWNfw2UReHTu4DyO+riQuqWZ1Myv4D5ukggVm/keV9oO7oQqF7c7ff86O6bSXJWLYim+UaNx2qDWLG3S7AaOIROvfa6X93kx5TLol+uoQLD7rF4bCa/Pyhh1zb7p17D1zCmmYvyqj0KKRRbcMkg5OJKrmfTlWJxofVDvMx7N7caYwWdmol6Odqotra827ZgMNKkM9qpFmuffbIRSA6gchVsHTEEQbQVs42WPpmBHUAiriEBOdUJOB8q9C+UHp71ulUeySVyUat7UMelBew5a2EOyJPgLGfLwx/KSd8nGR4KBAt4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
