appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: diHdHmMPf8gDrLB6TRlYwmAJVuGm3C3nMHlLJXj7RNEkFaWPoBiNbqiZQ+zDfs8cEJJFOFXODlO+u2YeY0by7ugitz8liDPjqlgTwO7d0KBur/WTnvcPGOgZSCZzzl0NW//PoEgIERaloOxe4ijTUL9dmbhIdrGjqcySzZFm1hPz/58Ww2ZRX/Fr69oorCZE0zxCzCKD9Zt+YLgMxe6UGOrk0QqwP6KXwT/+Hu4HbtqvBxRsRVHD59x8a6mQTLY9xn+7Ph/02IYGxYkPXsRlBbbhgRANJsVaYBEqoLZKRgGSvqmS4RnCPJ3AOcD9RrV8oa2exkK8jpP1lOJ42BtRazpEpxCNXiJ+sUz5AdUl+YYqAHl7til6ZsJVgnk/ucyL/LcDXNfa/2XGCgy6Ew6cO3nekanxE+AZJdcbfKoQJJEBmaaYsjGpU4vJNBs+ZMKoXAWwfsBCID17WanIJxL08Fqidjey1qTUTwqGN3HSbuMRslPcCPXSwwQAGbTZbuAV3hxu9vUYC4y/YOHf5GQmv73hAqoF/k11RByeLuIpPqjNuwFqNfGyO8Jqkr+ZAEwXWexqgSa7IYdZJq8sYcYMOKaAEsF/jPpao03AzdZJ746cN615O+dtLX1B8r4/qrL7ITlPCxET8uu1xQjsRQZR45RkA89PsXzlYHRWiSbH+9I=
conda_forge_output_validation: true
